### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by defeo** [defeo/cypari2#1]
- [x] Call `rebuild()` before cythonizing
- [x] Don't use Cythonize (see #7)
- [x] Figure out the `six` dependency (see https://trac.sagemath.org/ticket/22239)
- [x] Figure out build errors in `convert.pyx` (Python 3)
- [x] Python 3 compatibility (see #3)

Hard to do:
- [ ] Install `cython` and `cysignals` automatically upon `pip install`

**Comment by jdemeyer** [comment]
Why a `six` dependency? I don't think that we are using `six`, or am I missing something?

**Comment by videlec** [comment]
We do once

    $ grep -R six
    autogen/doc.py:from six import unichr

**Comment by jdemeyer** [comment]
Not anymore, see https://trac.sagemath.org/ticket/22239

**Comment by videlec** [comment]
Good. Let me port it in cypari2.

**Comment by jdemeyer** [comment]
We can do that later, there are still other things to be fixed in Sage first.

**Comment by videlec** [comment]
done in e92e229 (that way the issue can be closed and I checked the Python2/3 compatibility)

**Comment by jdemeyer** [comment]
About installing cysignals automatically: I don't think that this is easy to do. But instead, we could provide a nice error message in case that it's not installed. The same for Cython.

**Comment by videlec** [comment]
I guess we could close this issue?
