### ISSUE TITLE
a failure on travis

### ISSUE THREAD

**Issue by videlec** [defeo/cypari2#14]
The `IGNORE_EXCEPTION_DETAIL` flag of `doctest` hides a strange error appearing on travis with the following doctest

    >>> s = pari("x + O(x^2)")
    >>> gen_to_integer(s)

Travis complains that polynomial can not be converted to int while it should be a series!

**Comment by jdemeyer** [comment]
I finally looked into this issue and the cause is http://gcc.gnu.org/bugzilla/show_bug.cgi?id=56982

I added a fix in the Travis script to work around that bug and disabled `IGNORE_EXCEPTION_DETAIL` again.
