### ISSUE TITLE
make it so “... python setup.py install” immediately fails with a clear error message to use pip

### ISSUE THREAD

**Issue by williamstein** [defeo/cypari2#15]

**Comment by videlec** [comment]
Why would you like to force users to compile/install with pip? For example, we do want to support

    python setup.py build_ext --inplace

**Comment by williamstein** [comment]
The readme says that you must use pip.  I didn’t see that and just did `python setup.py install`, which resulted in a subtly broken install, which wasted my (really Rob Harron’s) time...  Of course, it would be much better if `python setup.py install` worked.

**Comment by jdemeyer** [comment]
I guess the "real" problem is that you don't want `setuptools` eggs. I have exactly the same problem with `cysignals` and solved it by creating a fake `bdist_egg` command which just raises an error: https://github.com/sagemath/cysignals/blob/master/setup.py#L183

**Comment by jdemeyer** [comment]
> Of course, it would be much better if python setup.py install worked.

I have had copious discussions with setuptools upstream, leading nowhere. They just don't seem to "get" that sometimes Python packages need to install data files (the Cython headers in this case) in "standard" locations and not in some setuptools-only format like an egg.

Luckily, pip solves this problem by going back to the distutils way of installing packages, just with a better interface.

**Comment by jdemeyer** [comment]
Fixed by #20.
