### ISSUE TITLE
Add access to idealmoddivisor function

### ISSUE THREAD

**Issue by rharron** [defeo/cypari2#17]
In order to implement ray class groups of number fields in Sage, an undocumented (and hence not automatically generated) function of libpari must be exposed. The function is called idealmoddivisor. I've created a fork, made the appropriate edit (basically three lines of code, plus a doctest), and made a pull request. This update is required for the update to Sage at https://trac.sagemath.org/ticket/15829.

**Comment by videlec** [comment]
corresponding issue is #16

**Comment by videlec** [comment]
Do you know why the function `idealmoddivisor` does not appear in `pari.desc` (ie not available from GP)? This function would better be autogenerated.

**Comment by rharron** [comment]
From an email exchange with Karim Belabas last year, it's that he views the function as "useless" in practice. Which, admittedly, is true from the standpoint of someone trying to write very fast code to do research computations. But, in Sage, from a user experience point of view, if you have a class in a ray class group, you might want to know an ideal representative of that class. In order to output a reasonably sized ideal representative in general, idealmoddivisor is needed, since that is exactly what it does. And so, in my code, the only time this function is used is when the user asks to see an ideal representative (and even then the user can ask for it not to be used); all computations are otherwise done in the efficient way of pari.

**Comment by videlec** [comment]
I agree with Karim's answer but I don't see why it forbids having it in `pari.desc`. GP is a user interface to the PARI library. Having `idealmoddivisor` there does make sense.

**Comment by rharron** [comment]
It could also be that because the function is viewed as "useless" no energy is being devoted to writing documentation for it, rather than such an endeavour being forbidden.

**Comment by videlec** [comment]
Did you proposed a patch to them? I understand that they will not write it but they might still accept it.

**Comment by jdemeyer** [comment]
This is fixed, right?

**Comment by videlec** [comment]
Yes
