### ISSUE TITLE
add documentation on readthedocs

### ISSUE THREAD

**Issue by videlec** [defeo/cypari2#18]
The HTML documentation should better be available on internet

**Comment by jdemeyer** [comment]
I have done this for https://github.com/fplll/fpylll, which is very similar to cypari2. It needs some tricks to install the dependencies on a conda env, but I should be able to do this.

**Comment by jdemeyer** [comment]
Working on this...

**Comment by jdemeyer** [comment]
@defeo @videlec I don't have the required admin access on this project to set up the webhook.

**Comment by videlec** [comment]
neither do I

**Comment by defeo** [comment]
Thx. I don't think I can give admin access for webhooks, as this is a personal repo. Only way would be to move to a team repo. Anyway, activating the webhook now.

**Comment by jdemeyer** [comment]
This fails to build due to (presumably) a bug in the Conda PARI package:
```
PARI data directory '/feedstock_root/build_artefacts/pari_1493573901811/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/share/pari' does not exist
```

**Comment by jdemeyer** [comment]
http://cypari2.readthedocs.io
