### ISSUE TITLE
real precision not always taken into account

### ISSUE THREAD

**Issue by videlec** [defeo/cypari2#2]
Perhaps it is a feature, but it is confusing

    >>> import cypari2
    >>> pari = cypari2.Pari()
    >>> pari(5.0).precision()
    3
    >>> pari("5.0").precision()
    3
    >>> pari.set_real_precision(200)
    15
    >>> pari(5.0).precision()
    3
    >>> pari("5.0").precision()
    13

**Comment by defeo** [comment]
It's documented in the pari_instance docstring: https://github.com/defeo/cypari2/blob/master/cypari2/pari_instance.pyx#L55-L205

I'm not sure we can do much better than this.

**Comment by jdemeyer** [comment]
Yes, it's a well-documented "feature".
