### ISSUE TITLE
closure_func_err

### ISSUE THREAD

**Issue by videlec** [defeo/cypari2#37]
On pari master `closure_func_err` is in `paridecl.h` and documented (see commit `14ba2ae` from March 31st 2017 and commit `8d621b1` from September 19th 2017). We should clean the pxd headers accordingly.

**Comment by jdemeyer** [comment]
> We should clean the pxd headers accordingly.

What do you propose? We support PARI-2.9 too.

The status quo works with all versions of PARI that we test. In the worst case, we have a harmless double declaration of the function `closure_func_err`. Why should we fix something that is not broken?

**Comment by videlec** [comment]
We might just change the misleading comment in
```
cdef extern:  # Declared in private PARI header file "anal.h"
    const char* closure_func_err()
```

**Comment by jdemeyer** [comment]
Fixed in https://github.com/defeo/cypari2/commit/0e6337176d5800fce63723a539fe3424a59f1a62
