### ISSUE TITLE
Fixing ellwp()?

### ISSUE THREAD

**Issue by jdemeyer** [defeo/cypari2#38]
There was an upstream bug (fixed very recently) in `ellwp()`: it was returning a derivative which was a factor 2 too small. This leads to obvious doctest failures with PARI master:
```
File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/cypari2/gen.so", line ?, in cypari2.gen.__test__.Gen.ellwp (line 4714)
Failed example:
    E.ellwp(1, flag=1)
Differences (ndiff with -expected +actual):
    - [13.9658695257485, 50.5619300880073]
    + [13.9658695257485, 101.123860176015]
```

The old (expected) result is wrong, the new result is correct.

This leads to a philosophical question: should cypari2 work around known PARI bugs or should it simply mindlessly call the PARI methods?

**Comment by jdemeyer** [comment]
Note that we need to do this workaround either here or in Sage. So maybe doing it here would be better.

**Comment by videlec** [comment]
I think that it is good to include bug fixes in cypari2. Though they would better be carefully documented and tested.

As we support different pari versions (ie some with the bug fix and some without), how can this be done in cypari2?

**Comment by jdemeyer** [comment]
Fixed in https://github.com/defeo/cypari2/commit/1a88bb4edc68eb8ff88d4978d99807f4b4df9ca5

**Comment by defeo** [comment]
Coming late to the party. I'm not convinced it is cypari2's responsibility to work around Pari bugs, especially if they get fixed upstream.
I'm fine with this change, I'm not asking to roll it back, but I would like to hear some good argument for keeping doing this in the future.
My feeling is that this adds unnecessary complexity to the code; I would rather change the doctest so that it passes regardless of the Pari version.

**Comment by jdemeyer** [comment]
> I would rather change the doctest so that it passes regardless of the Pari version.

How would you write a doctest if the result is mathematically wrong? We are not talking about a subtly different output here, we are talking about a complex number which is a factor 2 too small.

**Comment by jdemeyer** [comment]
> I'm not convinced it is cypari2's responsibility to work around Pari bugs, especially if they get fixed upstream.

One reason to fix it in cypari2 is related to distribution and packaging. If Sage switches to PARI master, we should try to keep it compatible with PARI stable too. Ideally, upstream PARI would make a bugfix release fixing this `ellwp()` bug. Then we could ask distros to use that. But since latest PARI stable has the bug and we want to support that version, we need to work around the bug either in cypari2 or in Sage.

Initially, I added a fix to Sage (https://trac.sagemath.org/ticket/23796) but given that `ellwp()` doctests were failing in cypari2 too, it actually makes sense to fix it in cypari2.

**Comment by defeo** [comment]
> How would you write a doctest if the result is mathematically wrong? We are not talking about a subtly different output here, we are talking about a complex number which is a factor 2 too small.

```
sage: ellwp() if version >= "2.x.x" else 2*ellwp()
<mathematically correct output>
```

**Comment by defeo** [comment]
> If Sage switches to PARI master, we should try to keep it compatible with PARI stable too. Ideally, upstream PARI would make a bugfix release fixing this ellwp() bug. Then we could ask distros to use that. But since latest PARI stable has the bug and we want to support that version, we need to work around the bug either in cypari2 or in Sage.

This is a Sage problem, not a cypari problem. So Sage should implement the workaround, in my opinion.

**Comment by jdemeyer** [comment]
> This is a Sage problem, not a cypari problem. So Sage should implement the workaround, in my opinion.

It's neither a Sage nor cypari2 problem. It is really an upstream PARI/GP problem

**Comment by defeo** [comment]
> It's neither a Sage nor cypari2 problem. It is really an upstream PARI/GP problem

If you wish.

Hence, if I am a user of cypari (other than Sage), I expect PARI to
fix it, not cypari. Once PARI has fixed the bug (because I submitted a
patch, or because the devs did it), I will update PARI to master, and
recompile cypari.

Let's say PARI adds a new function in master. Should we "work around"
the fact that the function is not present in stable by implementing it
in cypari?

This will lead to headaches for users, where an algorithm written in
Python+CyPari+PARI gives correct results, but the same algorithm
written in pure GP gives wrong results. They won't thank us for the
time lost debugging.

**Comment by videlec** [comment]
@defeo got a point: if cypari2 is thought as a scripting language for the pari library (the same as GP) then we should not fix bugs in cypari2.

**Comment by jdemeyer** [comment]
> Hence, if I am a user of cypari (other than Sage), I expect PARI to fix it, not cypari.

There is an actual bug to be fixed because Sage relies on `ellwp()`. A bug should be fixed as upstream as possible. Given that we cannot force PARI to release PARI-2.9.4, the next upstream is cypari2.

> ```ellwp() if version >= "2.x.x" else 2*ellwp()```

Sorry, but I think that this is worse than simply fixing the bug. Being unaware of a bug is fine, but actively documenting a bug instead of applying an easy fix is just silly.

> Let's say PARI adds a new function in master. Should we "work around" the fact that the function is not present in stable by implementing it in cypari? 

We sort of did that with `idealmoddivisor` in #17.

**Comment by jdemeyer** [comment]
@defeo and @videlec : is it acceptable to keep the current `ellwp()` workaround in the code? Or I should I revert this?

**Comment by defeo** [comment]
> @defeo and @videlec : is it acceptable to keep the current ellwp() workaround in the code? Or I should I revert this?

As already said, I'm fine with the workaround, I'm not asking to revert it.

I was mainly raising the issue for the future. As we don't seem to
agree, we may discuss this more at the next occasion.
