### ISSUE TITLE
Différent results between cypari2 and pari gp : ellL1 and ellanalyticrank

### ISSUE THREAD

**Issue by vinklein** [defeo/cypari2#43]
ellL1 cases :

Python
```
from cypari2 import Pari
pari = Pari()
pari.set_real_precision(38)
Out[4]: 15
L = pari.ellinit([0, 0, 1, 7, 6], precision=127);
pari.ellL1(L, 3, precision=127)
Out[6]: 98.900778292211279593460469548777701092
```

Gp
```
break[3]> default(realprecision,38);
break[3]> L = ellinit([0,0,1,7,6]);
break[3]> ellL1(L,3)
98.900778292211279593460469548777701093
```

Python
```
pari.ellL1(pari.ellinit([0, 1, 1, -2, 0]), 2, precision=127)
Out[7]: 1.5186330005768535404603852157894440382

```

Gp
```
break[3]> ellL1(ellinit([0,1,1,-2,0]),2)
1.5186330005768535404603852157894440381
```
ellanalyticrank case:

Python
```
x = pari.ellinit([-5187, 176830], precision=127)
pari.ellanalyticrank(x, precision=127)
Out[16]: [5, 9997.0334671722554999496820788093288438]
```

Gp
```
break[4]> x = [-5187, 176830]
[-5187, 176830]
break[4]> x=ellinit(x);
break[4]> ellanalyticrank(x)
[5, 9997.0334671722554999496820788093288461]
```

**Comment by jdemeyer** [comment]
You are using a different precision. Why do you think that 38 decimal digits is the same as 127 bits?

In GP, you can set the precision in bits using `default(realbitprecision,127)`. If you do that, the results should be the same.

**Comment by vinklein** [comment]
Yes you're right, the translation of precision settings from gp to cypari2 it's still confusing for me.
I basically took 127 because of this:
```
pari.set_real_precision(38)
pari.get_real_precision_bits()
Out[48]: 127
```

**Comment by jdemeyer** [comment]
I guess that's the real bug then.

**Comment by jdemeyer** [comment]
In any case, you can use a precision in bits in both cypari2 and GP. There should be no need to convert to a decimal precision.

**Comment by vinklein** [comment]
I see but im in the process of translating gp test into python unit test, and the gp use decimal precision, and you can't use a decimal precision in function call.
Whatever this a little off topic.

**Comment by jdemeyer** [comment]
The issue is that `cypari2` really only deals with precisions in bits. So the call `pari.set_real_precision(38)` is translated internally to `pari.set_real_precision_bits(127)`

In GP on the other hand, `default(realprecision, 38)` sets to precision in bits to 128.

**Comment by videlec** [comment]
Though, the following behavior is very confusing
```
>>> import cypari2
>>> pari = cypari2.Pari()
>>> pari.set_real_precision(100)
15
>>> pari.cos('1')
0.5403023058681397174
>>> pari.cos(1)
0.5403023058681397174
>>> pari('cos(1)')
0.5403023058681397174009366074429766037323104206179222276700972553811003947744717645179518560871830893
```
Why exact inputs (like integer above) are not considered by default at the current PARI precision?

**Comment by jdemeyer** [comment]
First of all, I made sure to document the confusing behaviour: http://cypari2.readthedocs.io/en/latest/pari_instance.html#input-precision-for-function-calls

So at least, it's a feature and not a bug.

Global state is typically considered to be bad for a library. And this `pari.set_real_precision()` is such global state. Other Python libraries which use `cypari2` should typically use `pari.sin(...)` and not `pari("sin(...)")`. They should not be affected by the user-set precision.
