### ISSUE TITLE
Travis confused because there are 2 pari snapshots

### ISSUE THREAD

**Issue by videlec** [defeo/cypari2#49]
Currently

- pari-2.9.3-63-g22ed32a
- pari-2.10-1868-gbef585b

So that in the script `.travis-install-pari.sh` the variable `PARI_VERSION` is set to `pari-2.9.3-63-g22ed32a pari-2.10-1868-gbef585b`.

**Comment by videlec** [comment]
`cut -d' ' -f1` should be good enough, testing going on at https://travis-ci.org/defeo/cypari2/builds/324051969

**Comment by jdemeyer** [comment]
The question is how to figure out what is the correct snapshot. Currently there is
```
pari-2.10-1918-gd2f6b64.tar.gz
pari-2.10.0.A2017c.tar.gz
```

**Comment by jdemeyer** [comment]
Maybe use the last modified? Look at http://pari.math.u-bordeaux.fr/pub/pari/snapshots/?C=M;O=D and take the first one in the list.

**Comment by jdemeyer** [comment]
Fixed in e493bdad25a5fe97039533228429242068650792
