### ISSUE TITLE
Test cypari2.gen fails and segfault on 32 bit architectures

### ISSUE THREAD

**Issue by tobihan** [defeo/cypari2#61]
Hi,

on Debian with pari 2.9.3 and python 2, the test cypari2.gen fails on all 32 bit architectures. The logs can be found at
https://buildd.debian.org/status/package.php?p=cypari2&suite=experimental

The output always looks a bit different, for example on armel

    Testing cypari2.gen
    **********************************************************************
    File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_2.7/build/cypari2/gen.so", line ?, in cypari2.gen.__test__.Gen.debug (line 4789)
    Failed example:
        pari('[1/2, 1 + 1.0*I]').debug()
    Differences (ndiff with -expected +actual):
        - [&=...] VEC(lg=3):...
        -   1st component = [&=...] FRAC(lg=3):...
        -     num = [&=...] INT(lg=3):... (+,lgefint=3):...
        -     den = [&=...] INT(lg=3):... (+,lgefint=3):...
        -   2nd component = [&=...] COMPLEX(lg=3):...
        -     real = [&=...] INT(lg=3):... (+,lgefint=3):...
        -     imag = [&=...] REAL(lg=3):... (+,expo=0):...
        + [&=00f1558c] VEC(lg=3):22000003 00f15580 00f1555c
        +   1st component = [&=00f15580] FRAC(lg=3):08000003 00f15574 00f15568
        +     num = [&=00f15574] INT(lg=3):02000003 (+,lgefint=3):40000003 00000001
        +     den = [&=00f15568] INT(lg=3):02000003 (+,lgefint=3):40000003 00000002
        +   2nd component = [&=00f1555c] COMPLEX(lg=3):0c000003 00f15550 00f15540
        +     real = [&=00f15550] INT(lg=3):02000003 (+,lgefint=3):40000003 00000001
        +     imag = [&=00f15540] REAL(lg=4):04000004 (+,expo=0):60000000 80000000 00000000
    free(): invalid next size (normal)
    ------------------------------------------------------------------------
    ------------------------------------------------------------------------
    E: Build killed with signal TERM after 150 minutes of inactivity

On i386 the program is aborted before the output is printed

    Testing cypari2.gen
    free(): invalid next size (fast)
    ------------------------------------------------------------------------
    /usr/lib/python2.7/dist-packages/cysignals/signals.i386-linux-gnu.so(+0x3420)[0xf6424420]
    /usr/lib/python2.7/dist-packages/cysignals/signals.i386-linux-gnu.so(+0x3f4c)[0xf6424f4c]
    /usr/lib/python2.7/dist-packages/cysignals/signals.i386-linux-gnu.so(+0x6463)[0xf6427463]
    linux-gate.so.1(__kernel_sigreturn+0x0)[0xf7747ca0]
    linux-gate.so.1(__kernel_vsyscall+0x9)[0xf7747c89]
    /lib/i386-linux-gnu/libc.so.6(gsignal+0xc2)[0xf745a0a2]
    /lib/i386-linux-gnu/libc.so.6(abort+0x1a0)[0xf745b7a0]
    /lib/i386-linux-gnu/libc.so.6(+0x6f24b)[0xf749c24b]
    /lib/i386-linux-gnu/libc.so.6(+0x75bde)[0xf74a2bde]
    /lib/i386-linux-gnu/libc.so.6(+0x775ab)[0xf74a45ab]
    /<<PKGBUILDDIR>>/.pybuild/pythonX.Y_2.7/build/cypari2/gen.so(+0x2489a)[0xf649789a]
    /<<PKGBUILDDIR>>/.pybuild/pythonX.Y_2.7/build/cypari2/pari_instance.so(+0x20daa)[0xf7002daa]
    python2(PyDict_Clear+0xc1)[0x566870e1]
    python2(+0x163728)[0x566d8728]
    python2(PyEval_EvalFrameEx+0x5d3f)[0x5664f64f]
    python2(PyEval_EvalCodeEx+0x539)[0x566477e9]
    python2(PyEval_EvalFrameEx+0x5a64)[0x5664f374]
    python2(PyEval_EvalCodeEx+0x539)[0x566477e9]
    python2(PyEval_EvalFrameEx+0x5a64)[0x5664f374]
    python2(PyEval_EvalCodeEx+0x539)[0x566477e9]
    python2(+0x10131c)[0x5667631c]
    python2(PyRun_FileExFlags+0x75)[0x56671b55]
    python2(PyRun_SimpleFileExFlags+0x17c)[0x5667163c]
    python2(Py_Main+0x6fd)[0x566214cd]
    python2(main+0x1b)[0x56620dbb]
    /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0xf7445783]
    python2(+0xabc90)[0x56620c90]
    ------------------------------------------------------------------------
    Failed to execute cysignals-CSI: No such file or directory
    ------------------------------------------------------------------------
    Unhandled SIGABRT: An abort() occurred.
    This probably occurred because a *compiled* module has a bug
    in it and is not properly wrapped with sig_on(), sig_off().
    Python will now terminate.

Any ideas?

**Comment by jdemeyer** [comment]
Please try cypari2 version 1.1.4

**Comment by tobihan** [comment]
That fixed it, thanks!
