### ISSUE TITLE
version() does not seem to match its documentation

### ISSUE THREAD

**Issue by saraedum** [defeo/cypari2#65]
In my recent beta of Sage I see the following behaviour:
```
sage: import cypari2
sage: cypari2.Pari().version()
[2, 10, 0]
```
However,
```
❯ ./sage -gp
GP/PARI CALCULATOR Version 2.10.0 (development git-88fb5b3)
```

From the docstring of `.version()` I would expect a different version number including the git commit hash. It's not terribly important; just wondering if this feature still exists or if the documentation should be adapted?

**Comment by jdemeyer** [comment]
cypari2 is just doing what upstream PARI/GP does. You would get the same in a GP session.
