### ISSUE TITLE
Drop support for older versions of PARI?

### ISSUE THREAD

**Issue by jdemeyer** [defeo/cypari2#67]
In https://trac.sagemath.org/ticket/25567 I noticed that cypari2 fails to compile with newer versions of PARI. The easiest solution would be to drop support for older versions. That is not as bad as it sounds, since cypari2 version 1.1.4 is still available for those who want it.

Any objections @videlec or @defeo?

**Comment by videlec** [comment]
It is bad.

**Comment by videlec** [comment]
I believe that commit `bdf0605` from PARI is to blame (nfzk datastructure changed), see change number 8
```
      8- the rnf struct from rnfinit has changed, the new format is not
         compatible with pari-2.9
```

**Comment by videlec** [comment]
Very few functions have changed we could easily use macros for them. Alternatively, we could keep a branch for older versions of PARI in which we would still merge bug fixes (if any).

**Comment by jdemeyer** [comment]
> Very few functions have changed we could easily use macros for them

Yes, I do think that the problem is fixable. I just asked in case you would say "I don't care about supporting older versions of PARI in newer cypari2 releases".
