### ISSUE TITLE
warnings calling "gphelp -raw"

### ISSUE THREAD

**Issue by videlec** [defeo/cypari2#72]
On Perl 5.28 a warning about regexp is shown when calling `gphelp -raw`. This happens during the autogeneration of the documentation in cypari2. See upstream bug report at http://pari.math.u-bordeaux.fr/cgi-bin/bugreport.cgi?bug=2070

**Comment by jdemeyer** [comment]
Upstream bug... not for cypari2.

**Comment by videlec** [comment]
Of course it is upstream. Though, cypari2 users might want to report to us, and it is good to advertize here that the bug is already known and (hopefully) taken care of upstream.
